# Numpy

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## checking dimensions

In [5]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## accessing Arrays

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
arr3d = np.array([
    [
        [1,2,3,4,5], 
        [6,7,8,9,10] 
    ],
    [
        [11,12,13,14,15], 
        [16,17,18,19,20]
    ]
    ])
print(arr3d.ndim)
print('2nd element on 1st row: ', arr3d[1, 1,0])

2nd element on 1st row:  2
3
2nd element on 1st row:  16


## slicing

`arr[start:end:step]`

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[1:7:2])

[2 3 4 5]
[2 4 6]


## shape
- shape of the matrix `(m,n)`

In [ ]:
arr = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8]
    ])

print(arr.shape)

(2, 4)


## sorting

In [15]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


# Pandas

In [18]:
import pandas as pd
data = {
    "name": ["Tom","jack","steve","ricky"],
    "age": [28,34,29,42]
}
df = pd.DataFrame(data)
print(df.shape)
print(df)

df2 = pd.Series(data)
print(df2.shape)
print(df2)

(4, 2)
    name  age
0    Tom   28
1   jack   34
2  steve   29
3  ricky   42
(2,)
name    [Tom, jack, steve, ricky]
age              [28, 34, 29, 42]
dtype: object
